completions : 
  models: ['gpt-3.5-turbo', 'gpt-3.5-turbo-16k','gpt-4','Qwen-7B']
  max_tokens : 512
  temperature : 0.7
  top_p : 1.0
  stream : True
  num_tokens : True
  use_time : True
  system_prompt : "You are a hellpful assistant."